
name: Replicating error
on:
  push:
  workflow_dispatch:

jobs:
  check-semantics:
    name: Replicating error
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: debug
        uses: GarnerCorp/super-duper-lamp@main

