name: Checking Config Correctness
on:
  push:
  pull_request:

jobs:
  check-semantics:
    name: Checking Config Semantics
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          hostname -i
          ip -4 addr list
